---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##讀取SportsAnalytics中的NBA14-15資料

```{r echo=T}
#install.packages("SportsAnalytics")
library(SportsAnalytics)
NBA1415<-fetch_NBAPlayerStatistics("14-15")
```

##各隊最辛苦的球員

計算依據為各隊全季總出場分鐘數最多的球員

```{r echo=T}
MaxMinutesPlayed<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
NBA1415MaxMinutesPlayed<-merge(NBA1415,MaxMinutesPlayed)
output<-NBA1415MaxMinutesPlayed[order(NBA1415MaxMinutesPlayed$TotalMinutesPlayed,decreasing = T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digits=2)
```


##各隊得分王

計算依據為各隊全季總得分最多的球員

```{r echo=T}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
#tapply(NBA1415$TotalPoints,NBA1415$Team,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digits=2)
```	


##各隊最有效率的球員

計算依據為各隊(全季總得分/ 出戰分鐘數）最高的球員

```{r echo=T}
NBA1415$Efficiency <- NBA1415$TotalPoints / NBA1415$TotalMinutesPlayed
MaxEfficiency<-aggregate(Efficiency~Team,NBA1415,max)
NBA1415MaxEfficiency<-merge(NBA1415,MaxEfficiency)
output<-NBA1415MaxEfficiency[order(NBA1415MaxEfficiency$Efficiency,decreasing = T),c("Team","Name","Efficiency")]
library(knitr)
kable(output, digits=2)
```	


##各隊三分球出手最準的球員

計算依據為各隊(三分球進球次數/ 三分球出手次數）最高的球員

```{r echo=T}
NBA1415$Threepointshot<-NBA1415$ThreesMade/NBA1415$ThreesAttempted
bestThreeponit<-aggregate(Threepointshot~Team,NBA1415,max)
NBA1415bestThreeponit<-merge(NBA1415,bestThreeponit)
output2<-NBA1415bestThreeponit[order(NBA1415bestThreeponit$Threepointshot,decreasing = T),c("Team","Name","Threepointshot")]
library(knitr)
kable(output2, digits=2)
knitr::opts_chunk$set(echo = TRUE)
```
